### ISSUE TITLE
Pam's harvestcraft 1.12.2zg.jar not downloading

### ISSUE THREAD

**Issue by jav76** [EnigmaticaModpacks/Enigmatica2Expert#2025]
### Modpack Version

1.83

### Describe your issue.

When starting a new server I noticed that pam's harvestcraft didn't seem to be working. Looking at the logs I found that there was an issue with forge unable to read the jar file for Pam's:
`[12:43:07] [main/ERROR] [FML]: Unable to read the jar file Pam's HarvestCraft 1.12.2zg.jar - ignoring
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_333]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_333]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_333]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_333]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_333]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:366) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupServer(FMLLaunchHandler.java:87) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForServerLaunch(FMLLaunchHandler.java:47) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLServerTweaker.injectIntoClassLoader(FMLServerTweaker.java:62) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_333]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_333]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_333]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70) [forge-1.12.2-14.23.5.2855.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34) [forge-1.12.2-14.23.5.2855.jar:?]
[12:43:07] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.`

Looking in the mods directory the Pam's harvestcraft .jar file was 0KB. 
I was able to repeat this with the 1.83 tag by just running InstanceSync.jar, and then sorting the mods directory by size. Every time I delete the mods directory and run InstanceSync.jar again, the Pam's harvestcraft jar is still 0KB. I'm not really sure how pulling in the mods normally works, so I'm not sure if this is an issue with a newer version of Pam's or if I'm doing something wrong. Might be an issue with how it's defined in minecraftinstance.json?

### Latest Log

https://gist.github.com/jav76/4519724073ddb0beb9093c1282bdf4ba

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
A reinstall probably fixes that :)

**Comment by Quezler** [comment]
> A reinstall probably fixes that :)

looks like the instancesync didn't fancy the spaces in pam's filename not being encoded as `%20` 😗
https://discord.com/channels/195234321836146688/544589452492931076/974376198568312892

**Comment by jav76** [comment]
This was a pretty simple fix of just modifying InstanceSync to replace all spaces in download URIs to "%20"
I forked InstanceSync and made this change and built a jar to test and it seems to work as expected. 
[https://github.com/jav76/InstanceSync](https://github.com/jav76/InstanceSync)

To be quite honest I've never used Java before so while this does _work_, I would be skeptical and make sure that everything is done as it should be. This jar was built using openJDK 1.8.0_311. May be better to download the source and build your own jar since I'm sure you know what you're doing more than I do.
